use bb;

fn main() -> Result<(), failure::Error> {
    bb::run()
}
